variable "aws_lb_controller_version" {}
variable "aws_region" {}
variable "cluster_name" {}
variable "eks_node_group_ami" {}
variable "eks_version" {}
variable "external_dns_version" {}
variable "hosted_zone_id" {}
variable "subnet_ids" {}
variable "vpc_id" {}
