name: "Integration Tests"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  inspec:
    name: "Integration Tests"
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::533618305027:role/github-oidc
          aws-region: us-west-2
            
      - name: Inspec
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
          cd tests/integration/profile
          inspec exec . -t aws:// --chef-license accept
